pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                // Declarative checkout step
                checkout scm
            }
        }
        stage('Build') {
            steps {
                echo 'Step One - build is done'
               build 'JobA'
            }
        }
        stage('Test') {
            steps {
                echo 'Hello Test'
             
            }
        }
    }
    post {
        always{
            echo "ran successsfully"
            emailext body: 'Test Body content', subject: 'Test Email From Jenkins', to: 'shiva509203@gmail.com'
        }
        
    }
}
